# Pega esto en tu archivo .streamlit/secrets.toml

[firebase_credentials]

type = "service_account"
project_id = "waterconsumption-c2714"
private_key_id = "0df9e751bb45928c2ef88b6f37657ed95b803222"
client_email = "firebase-adminsdk-fbsvc@waterconsumption-c2714.iam.gserviceaccount.com"
client_id = "113860115615886375370"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40waterconsumption-c2714.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# La parte más importante:
# Usar comillas triples (""") le dice a TOML que respete
# los saltos de línea de tu llave privada.
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwD4mGYMkBBv+X
cHuVxMv+Q9m5SCp28wkuqpYuLAZcP55M6ndJpPnRPmICUkuHPyh6oH2yOScJBhqL
OVvBoBm/IvbwvePjhe+ZuvuVh1Wph+MbSNumUw6KX97UtYKJvdL4YLbQgaXsYB50
8mk18qaMV68aAPCVo+hC8K0L/JMSRRg+zBP6TxXYtVCSIvO7SPvBH/+mCaClayd6
Gvp3Y74OCFxwkxVZb20qu6Oo3+UQES8Sy8saf1q3REfDy14lmjuUfVk3aD89EyCR
GxRxp/rNHiAvabcBqrRq+tvaZpMf5WcHAXUkqL6sLXfUN+hzjSLih4Rsb6X56AU8
T9E4KzoBAgMBAAECggEAQXql1Tptx1oI+RO2gu8cR0aI1SYH1RFyms6K6EUrYGew
wj55ewRGfRHMdbyRpo1QyrqhxQUIhYyllp4QiCS5LqMcYFDfTqFjiTNHmkcpDtIh
Huar+mHtiH07bLTNBdl5ezLNCyMMyKq+6RO3GX9TfeKmlu8+iwjYuvyz/z9Cm4pE
u8zDTJBFmBK5LPNfCXfhDzJSXQFl9hYaRqNGuOYw4W2kuoKycUxQpD51UCHO7wXZ
ldWwdr4X9sbTtByxxUzKmIxt7udHEsi6GuO9heULt6M8qwYWwst2ZsVglCX/RJnj
b6eTE4H77cA/Bml6ob+ktMoWm0tPJ3C6MqpMKVfvuQKBgQDjlI0qJ9SV2X+WrWRt
BJLnnoTHGEawgMwccR2A6TgJNtQQn3m8UcsTxJIasLXMYlr6g6lsqOm5F1+h4ytU
arVlVTD2ilsCsUr8zyqub9aPsq0TvTwXMC8fE7TSArsHHqmV4kTvw4BLwEvgpqkh
xo/qyh3qbSASjIkpYhndthSX6wKBgQDGC/iNggezWln9iUdGfVWSU+9VYYvfB1E2
TLfYwK44DE1KqOurtaBr9mYZluUZ/kLwZeLX+tTvnFW32UTUy4ZVARwhL7I9Ii/Q
3zkYinS+eAjFjE09lcKnspwmGbpXW4a5U9ecbseeAeonIAZKCMhM3aEgcS9pN+P6
QSKIccQGwwKBgQCiKTW1NhBqfkJFsWN/suSimfdujkPAfOXz1j35nzTIjALrnVb2
8ylK+qRI1GWWLvc4zhwpSurPcnI4PlCfpDGA9QUgh1F2R7JxFYUKKrKuTdi52fs5
YqIQ+M+9XSi7WAPqwwHv/lQqpejrOJYHdR8TY9WRNxTFYtJRZI+dxaJC5QKBgQCC
hz1INt1QbkpFegcKBG0zxjJFucbwNehmu2WobEXnFuSSQochYtHalklwsC1LVnNT
8jLyWpWhXw5337En9wQQXmzlyoPVGwUcyyLcc9TB/Gb7nJ8D6gKjeGrGCcrw7Jf8
6a9/oNvb3jMvmkHK5cLuNlyN/0taM8YEGI3kE+c49QKBgHRaN4qvygsBQ4bgJ0iu
kuSA4iBQgwqzo4osQF11QUfcT3iCFFzzMQcKeFlaN4jykA7riIUULSc228FKZ1s3
iULe8YF+BxWenqjJDSVr/PylLRiV0h44G7/6UMnNPYXNC/af+sDEPmxUpe2mUS0V
s2l88HSdFbKonA6c8adJBGMj
-----END PRIVATE KEY-----
"""